package qudy

import (
	"fmt"
	"go/format"
)

// outVariable names a function's emit function in a package with a runtime file.
const outVariable = "qudyOut"

// outDecl returns the declaration of qudyOut, which prefers qudyEmit over the emit function.
func outDecl(emit string) string {
	return outVariable + " := qudyDispatch(func(format string, args ...any) { " + emit + "(format, args...) })"
}

// runtimeFile is the source of the runtime file, before its package clause.
const runtimeFile = `// Code generated by qudy -runtime. DO NOT EDIT.

package %s

import (
	"fmt"
	"strings"
)

// qudyEmit replaces the -emit function while it is set.
var qudyEmit func(format string, args ...any)

// qudyPush sets the emit function and returns the call that restores the previous one.
func qudyPush(emit func(format string, args ...any)) (pop func()) {
	previous := qudyEmit
	qudyEmit = emit
	return func() { qudyEmit = previous }
}

// qudyCapture runs f and returns the text of its output lines.
func qudyCapture(f func()) string {
	var text strings.Builder
	defer qudyPush(func(format string, args ...any) { fmt.Fprintf(&text, format, args...) })()
	f()
	return text.String()
}

// qudyDispatch returns an emit function that prefers qudyEmit over fallback.
func qudyDispatch(fallback func(format string, args ...any)) func(format string, args ...any) {
	return func(format string, args ...any) {
		if qudyEmit != nil {
			qudyEmit(format, args...)
			return
		}
		fallback(format, args...)
	}
}

// qudyCount numbers the gensyms of the run.
var qudyCount int

// qudyGensym returns a name that differs from every gensym of the enclosing scopes.
func qudyGensym(want string) string {
	qudyCount++
	return fmt.Sprintf("%%s` + gensymSuffix + `%%d", want, qudyCount)
}

// qudyScope starts a scope of the generated program and returns its end.
func qudyScope() func() {
	saved := qudyCount
	return func() { qudyCount = saved }
}
`

// runtimeSource returns the runtime file for a package.
func runtimeSource(pkg string) ([]byte, error) {
	return format.Source([]byte(fmt.Sprintf(runtimeFile, pkg)))
}
