// Code generated by qudy from compiler.go. DO NOT EDIT.

//go:build !qudy || generate

package main

import (
	"fmt"
	"go/token"
	"os"
	"strconv"
	"strings"
	"text/scanner"
	"unicode"
)

// A reader form retains only delimiters, atoms, metadata and source position.
// There are no nodes for calls, bindings, functions or other language constructs.
type form struct {
	atom  string
	delim rune
	kids  []form
	hint  string
	pos   scanner.Position
}

func fail(f form, message string) { panic(fmt.Errorf("%s: %s", f.pos, message)) }

func need(f form, ok bool, message string) {
	if !ok {
		fail(f, message)
	}
}

func read(s *scanner.Scanner, t rune) form {
	f := form{atom: s.TokenText(), pos: s.Position}
	if t == '^' {
		hint := read(s, s.Scan())
		f = read(s, s.Scan())
		f.hint = typeName(hint)
		return f
	}
	need(f, t != scanner.EOF && t != ')' && t != ']', "unexpected end or closing delimiter")
	if t != '(' && t != '[' {
		return f
	}
	f.delim, f.atom = t, ""
	close := ')'
	if t == '[' {
		close = ']'
	}
	for t = s.Scan(); t != close; t = s.Scan() {
		if t == ';' {
			for s.Peek() != '\n' && s.Peek() != scanner.EOF {
				s.Next()
			}
			continue
		}
		f.kids = append(f.kids, read(s, t))
	}
	return f
}

func ident(f form) string {
	name := f.atom
	need(f, !strings.HasPrefix(name, "_lispg"), "_lispg is reserved for generated names")
	if token.Lookup(name).IsKeyword() {
		name = "_lispg_" + name
	}
	need(f, f.delim == 0 && name != "_" && token.IsIdentifier(name), "expected an identifier")
	return name
}

func typ(f form, t string) string {
	need(f, t != "", "expected a type hint")
	return t
}

func typeName(f form) string {
	qudyOut := qudyDispatch(func(format string, args ...any) { emit(format, args...) })
	return qudyCapture(func() {
		switch f.delim {
		case '[':
			arity(f, f.kids, 1, 1)
			qudyOut(`[]%v`, typeName(f.kids[0]))
		case '(':
			head, args := parts(f)
			arity(f, args, 2, 2)
			need(f, head == "fn" && args[0].delim == '[', "expected (fn [argument types] result type)")
			var params []string
			for _, p := range args[0].kids {
				params = append(params, typeName(p))
			}
			qudyOut(`func(`)
			for qudyI, qudyX := range params {
				if qudyI > 0 {
					qudyOut(", ")
				}
				qudyOut("%v", qudyX)
			}
			qudyOut(`) %v`, typeName(args[1]))
		default:
			name := strings.Split(f.atom, ".")
			qualified := len(name) == 2 && token.IsIdentifier(name[0]) && token.IsIdentifier(name[1])
			need(f, qualified || f.atom == "error" || f.atom == "int64" || f.atom == "float64" || f.atom == "string" || f.atom == "bool", "unknown type")
			qudyOut(`%v`, f.atom)
		}
	})
}

func parts(f form) (string, []form) {
	need(f, f.delim == '(' && len(f.kids) > 0, "expected a nonempty list")
	return f.kids[0].atom, f.kids[1:]
}

func arity(f form, args []form, min, max int) {
	need(f, len(args) >= min && len(args) <= max, "wrong number of arguments")
}

// emit is Qudy's printf target. A write error must also fail the transpiler.
func emit(format string, args ...any) {
	if _, err := fmt.Printf(format, args...); err != nil {
		panic(err)
	}
}

func atom(f form) {
	qudyOut := qudyDispatch(func(format string, args ...any) { emit(format, args...) })
	s := f.atom
	need(f, s != "", "expected an atom")
	if strings.HasPrefix(s, "\"") {
		_, err := strconv.Unquote(s)
		need(f, err == nil, "invalid string")
		qudyOut(`%v`, s)
	} else if n, err := strconv.ParseInt(s, 10, 64); err == nil {
		qudyOut(`int64(%v)`, n)
	} else if strings.ContainsAny(s, ".eE") && numeric(s) {
		_, err := strconv.ParseFloat(s, 64)
		need(f, err == nil, "invalid float64 literal")
		qudyOut(`float64(%v)`, s)
	} else {
		segments := strings.Split(s, ".")
		for i, p := range segments {
			segments[i] = ident(form{atom: p, pos: f.pos})
		}
		qudyOut(`%v`, strings.Join(segments, "."))
	}
}

func numeric(s string) bool {
	s = strings.TrimLeft(s, "+-")
	return len(s) > 0 && (s[0] >= '0' && s[0] <= '9' || s[0] == '.')
}

// A known result type flows down from a function return or a ^type hint.
// Go checks ordinary calls, names and operand types in the emitted program.
func expr(f form, want string) {
	qudyOut := qudyDispatch(func(format string, args ...any) { emit(format, args...) })
	if f.hint != "" {
		want = typ(f, f.hint)
	}
	if f.delim == 0 {
		atom(f)
		return
	}
	if f.delim == '[' {
		listExpr(f, want)
		return
	}
	head, args := parts(f)
	switch head {
	case "if", "when", "let":
		need(f, want != "", "expression needs a ^type hint or a typed function result")
		qudyOut(`func() %v {
`, want)
		localExpr(f, want)
		qudyOut(`}()`)
	case "fn":
		arity(f, args, 2, len(args))
		params, result := args[0], args[0].hint
		qudyOut(`func(%v) %v {
`, parameters(params), result)
		body(args[1:], result)
		qudyOut(`}`)
	case "defn", "package", "import":
		fail(f, head+" can only be used at top level")
	case "+", "-", "*", "/", "%", "=", "not=", "<", "<=", ">", ">=", "and", "or", "not":
		operator(f, head, args, want)
	default:
		helper := map[string]string{"first": "First", "rest": "Rest", "empty?": "Empty", "cons": "Cons"}[head]
		if helper != "" {
			n := 1
			if head == "cons" {
				n = 2
			}
			arity(f, args, n, n)
			qudyOut(`_lispg%v`, helper)
		} else {
			expr(f.kids[0], "")
		}
		qudyOut(`(`)
		for i, a := range args {
			if i > 0 {
				qudyOut(`, `)
			}
			t := ""
			if head == "rest" || head == "cons" {
				t = want
			}
			if head == "first" && want != "" {
				t = "[]" + want
			}
			if head == "cons" && i == 0 {
				t = strings.TrimPrefix(t, "[]")
			}
			expr(a, t)
		}
		qudyOut(`)`)
	}
}

func listExpr(f form, want string) {
	qudyOut := qudyDispatch(func(format string, args ...any) { emit(format, args...) })
	need(f, want == "" || strings.HasPrefix(want, "[]"), "expected a list type")
	need(f, want != "" || len(f.kids) > 0, "empty list needs a type hint or context")

	elem := strings.TrimPrefix(want, "[]")
	qudyOut(`_lispgList`)
	if want != "" {
		qudyOut(`[%v]`, elem)
	}
	qudyOut(`(`)
	for i, item := range f.kids {
		if i > 0 {
			qudyOut(`, `)
		}
		expr(item, elem)
	}
	qudyOut(`)`)
}

func operator(f form, op string, args []form, want string) {
	qudyOut := qudyDispatch(func(format string, args ...any) { emit(format, args...) })
	min, max := 2, len(args)
	if op == "-" {
		min = 1
	}
	if strings.Contains(" = not= < <= > >= % ", " "+op+" ") {
		max = 2
		want = ""
	}
	if op == "and" || op == "or" || op == "not" {
		want = "bool"
	}
	if op == "not" {
		min, max = 1, 1
	}
	arity(f, args, min, max)
	if goOp, ok := map[string]string{"=": "==", "not=": "!=", "and": "&&", "or": "||", "not": "!"}[op]; ok {
		op = goOp
	}
	qudyOut(`(`)
	if len(args) == 1 {
		qudyOut(`%v`, op)
	}
	for i, a := range args {
		if i > 0 {
			qudyOut(` %v `, op)
		}
		expr(a, want)
	}
	qudyOut(`)`)
}

// Return declarations only; the caller owns the function's delimiters and result.
func parameters(params form) string {
	qudyOut := qudyDispatch(func(format string, args ...any) { emit(format, args...) })
	need(params, params.delim == '[', "expected parameter vector")
	return qudyCapture(func() {
		seen := map[string]bool{}
		for i, p := range params.kids {
			name, t := ident(p), typ(p, p.hint)
			need(p, !seen[name], "duplicate parameter")
			seen[name] = true
			if i > 0 {
				qudyOut(`, `)
			}
			qudyOut(`%v %v`, name, t)
		}
	})
}

func body(forms []form, result string) {
	qudyOut := qudyDispatch(func(format string, args ...any) { emit(format, args...) })
	if len(forms) == 0 {
		zero(result)
	}
	for i, f := range forms {
		if i == len(forms)-1 && result != "" {
			qudyOut(`return `)
			expr(f, result)
			qudyOut(`
`)
		} else {
			discardExpr(f)
		}
	}
}

// An absent branch or empty body yields the result type's zero value.
func zero(result string) {
	qudyOut := qudyDispatch(func(format string, args ...any) { emit(format, args...) })
	if result != "" {
		qudyOut(`var _lispgZero %v; return _lispgZero
`, result)
	}
}

func conditional(args []form, result string) {
	qudyOut := qudyDispatch(func(format string, args ...any) { emit(format, args...) })
	qudyOut(`if `)
	expr(args[0], "bool")
	qudyOut(` {
`)
	body(args[1:2], result)
	if len(args) == 3 {
		qudyOut(`} else {
`)
		body(args[2:3], result)
	}
	qudyOut(`}
`)
	if len(args) == 2 {
		zero(result)
	}
}

func binding(f form, args []form, result string) {
	qudyOut := qudyDispatch(func(format string, args ...any) { emit(format, args...) })
	arity(f, args, 1, len(args))
	v := args[0]
	need(v, v.delim == '[' && len(v.kids)%2 == 0, "expected name/value binding pairs")
	// Each nested scope lets an initializer see the previous binding of its name.
	for i := 0; i < len(v.kids); i += 2 {
		name := ident(v.kids[i])
		qudyOut(`{
`)
		t := v.kids[i].hint
		if t != "" {
			typ(v.kids[i], t)
			qudyOut(`var %v %v = `, name, t)
		} else {
			qudyOut(`%v := `, name)
		}
		expr(v.kids[i+1], t)
		qudyOut(`
_ = %v
`, name)
	}
	body(args[1:], result)
	for i := 0; i < len(v.kids); i += 2 {
		qudyOut(`}
`)
	}
}

// Emit the same expressions without materializing a result when it is discarded.
func localExpr(f form, result string) {
	qudyOut := qudyDispatch(func(format string, args ...any) { emit(format, args...) })
	head, args := parts(f)
	switch head {
	case "if":
		arity(f, args, 2, 3)
		conditional(args, result)
	case "when":
		arity(f, args, 1, len(args))
		qudyOut(`if `)
		expr(args[0], "bool")
		qudyOut(` {
`)
		body(args[1:], result)
		qudyOut(`}
`)
		zero(result)
	case "let":
		qudyOut(`{
`)
		binding(f, args, result)
		qudyOut(`}
`)
	}
}

func discardExpr(f form) {
	qudyOut := qudyDispatch(func(format string, args ...any) { emit(format, args...) })
	if f.delim == '(' {
		head, _ := parts(f)
		switch head {
		case "if", "when", "let":
			localExpr(f, "")
			return
		}
		// Calls may return zero, one, or several values; Go discards them here.
		if head != "fn" && !strings.Contains(" + - * / % = not= < <= > >= and or not ", " "+head+" ") {
			expr(f, "")
			qudyOut(`
`)
			return
		}
	}
	qudyOut(`_ = `)
	expr(f, "")
	qudyOut(`
`)
}

func namespaceExpr(f form, stage *int) {
	qudyOut := qudyDispatch(func(format string, args ...any) { emit(format, args...) })
	head, args := parts(f)
	switch head {
	case "package":
		arity(f, args, 1, 1)
		need(f, *stage == 0, "package must appear once, first")
		name := ident(args[0])
		qudyOut(`package %v
`, name)
		*stage = 1
	case "import":
		need(f, *stage == 1, "imports must follow package and precede functions")
		for _, a := range args {
			path, err := strconv.Unquote(a.atom)
			need(a, a.delim == 0 && err == nil && path != "", "expected quoted import path")
			qudyOut(`import %q
`, fmt.Sprint(path))
		}
	case "defn":
		arity(f, args, 3, len(args))
		need(f, *stage > 0, "package must come first")
		*stage = 2
		need(args[0], args[0].hint == "", "put the return type hint before the parameter vector")
		name, result := ident(args[0]), args[1].hint
		qudyOut(`func %v(%v) %v {
`, name, parameters(args[1]), result)
		body(args[2:], result)
		qudyOut(`}
`)
	default:
		fail(f, "expected package, import or defn")
	}
}

func main() {
	qudyOut := qudyDispatch(func(format string, args ...any) { emit(format, args...) })
	defer func() {
		if e := recover(); e != nil {
			fmt.Fprintln(os.Stderr, "lispg:", e)
			os.Exit(1)
		}
	}()
	in := os.Stdin
	if len(os.Args) > 2 {
		panic(fmt.Errorf("usage: lispg [source.lisp]"))
	}
	if len(os.Args) == 2 {
		var err error
		in, err = os.Open(os.Args[1])
		if err != nil {
			panic(err)
		}
		defer in.Close()
	}
	var s scanner.Scanner
	s.Init(in)
	s.Filename = in.Name()
	s.Mode = scanner.ScanIdents | scanner.ScanStrings
	s.Whitespace |= 1 << ','
	s.IsIdentRune = func(r rune, i int) bool {
		return r != scanner.EOF && !unicode.IsSpace(r) && !strings.ContainsRune("()[]^;\",", r)
	}
	s.Error = func(s *scanner.Scanner, msg string) { panic(fmt.Errorf("%s: %s", s.Position, msg)) }
	stage := 0
	for t := s.Scan(); t != scanner.EOF; t = s.Scan() {
		if t == ';' {
			for s.Peek() != '\n' && s.Peek() != scanner.EOF {
				s.Next()
			}
			continue
		}
		namespaceExpr(read(&s, t), &stage)
	}
	if stage == 0 {
		panic(fmt.Errorf("missing package form"))
	}
	qudyOut(`func _lispgList[T any](xs ...T) []T { return xs }
func _lispgFirst[T any](xs []T) T { return xs[0] }
func _lispgRest[T any](xs []T) []T { if len(xs) == 0 { return xs }; return xs[1:] }
func _lispgEmpty[T any](xs []T) bool { return len(xs) == 0 }
func _lispgCons[T any](x T, xs []T) []T { return append([]T{x}, xs...) }
`)
}
