// Code generated by qudy -runtime. DO NOT EDIT.

package main

import (
	"fmt"
	"strings"
)

// qudyEmit replaces the -emit function while it is set.
var qudyEmit func(format string, args ...any)

// qudyPush sets the emit function and returns the call that restores the previous one.
func qudyPush(emit func(format string, args ...any)) (pop func()) {
	previous := qudyEmit
	qudyEmit = emit
	return func() { qudyEmit = previous }
}

// qudyCapture runs f and returns the text of its output lines.
func qudyCapture(f func()) string {
	var text strings.Builder
	defer qudyPush(func(format string, args ...any) { fmt.Fprintf(&text, format, args...) })()
	f()
	return text.String()
}

// qudyDispatch returns an emit function that prefers qudyEmit over fallback.
func qudyDispatch(fallback func(format string, args ...any)) func(format string, args ...any) {
	return func(format string, args ...any) {
		if qudyEmit != nil {
			qudyEmit(format, args...)
			return
		}
		fallback(format, args...)
	}
}

// qudyCounts counts the gensyms of each name for the whole run.
var qudyCounts = map[string]int{}

// qudyGensym returns a name that differs from every other gensym of this generator.
func qudyGensym(want string) string {
	qudyCounts[want]++
	return fmt.Sprintf("%s_qd%d", want, qudyCounts[want])
}
