// Code generated by qudy -runtime. DO NOT EDIT.

package main

import (
	"fmt"
	"strings"
)

// qudyEmit replaces the -emit function while it is set.
var qudyEmit func(format string, args ...any)

// qudyPush sets the emit function and returns the call that restores the previous one.
func qudyPush(emit func(format string, args ...any)) (pop func()) {
	previous := qudyEmit
	qudyEmit = emit
	return func() { qudyEmit = previous }
}

// qudyCapture runs f and returns the text of its output lines.
func qudyCapture(f func()) string {
	var text strings.Builder
	defer qudyPush(func(format string, args ...any) { fmt.Fprintf(&text, format, args...) })()
	f()
	return text.String()
}

// qudyDispatch returns an emit function that prefers qudyEmit over fallback.
func qudyDispatch(fallback func(format string, args ...any)) func(format string, args ...any) {
	return func(format string, args ...any) {
		if qudyEmit != nil {
			qudyEmit(format, args...)
			return
		}
		fallback(format, args...)
	}
}

// qudyCount numbers the gensyms of the run.
var qudyCount int

// qudyGensym returns a name that differs from every gensym of the enclosing scopes.
func qudyGensym(want string) string {
	qudyCount++
	return fmt.Sprintf("%s_qd%d", want, qudyCount)
}

// qudyScope starts a scope of the generated program and returns its end.
func qudyScope() func() {
	saved := qudyCount
	return func() { qudyCount = saved }
}
