// Code generated by qudy from write.go. DO NOT EDIT.

//go:build !qudy

//line write.go:3
package main

import "fmt"

// writeParse writes the file with the function that parses an enum's constant names.
//
//line write.go:6
func writeParse(file, pkg, typ string, names []string) {
	qudyGensym := func() func(string) string {
		count := 0
		gensym := func(want string) string {
			count++
			digits := ""
			for n := count; n > 0; n /= 10 {
				digits = string(rune('0'+n%10)) + digits
			}
			return want + "_qd" + digits
		}
		return gensym
	}()
	s_qd := qudyGensym("s")
//line write.go:7
	fmt.Printf(`-- %v_parse.go --
// Code generated by the qudy enums example. DO NOT EDIT.

package %v

import "fmt"

// Parse%v returns the %v with the given name.
func Parse%v(%v string) (%v, error) {
	switch %v {
`, /*line write.go:7*/ file /*line write.go:10*/, pkg /*line write.go:14*/, typ, typ /*line write.go:15*/, typ, s_qd, typ /*line write.go:16*/, s_qd)
//line write.go:17
	for _, name := range names {
//line write.go:18
		fmt.Printf(`	case "%v":
		return %v, nil
`, /*line write.go:18*/ name /*line write.go:19*/, name)
//line write.go:20
	}
	zero_qd := qudyGensym("zero")
//line write.go:21
	fmt.Printf(`	}
	var %v %v
	return %v, fmt.Errorf("%v has no constant named %%q", %v)
}
`, /*line write.go:22*/ zero_qd, typ /*line write.go:23*/, zero_qd, typ, s_qd)
//line write.go:25
}

// writeString writes the file with an enum's String method.
func writeString(file, pkg, typ string, names []string) {
	qudyGensym := func() func(string) string {
		count := 0
		gensym := func(want string) string {
			count++
			digits := ""
			for n := count; n > 0; n /= 10 {
				digits = string(rune('0'+n%10)) + digits
			}
			return want + "_qd" + digits
		}
		return gensym
	}()
	v_qd := qudyGensym("v")
//line write.go:29
	fmt.Printf(`-- %v_string.go --
// Code generated by the qudy enums example. DO NOT EDIT.

package %v

import "fmt"

func (%v %v) String() string {
	switch %v {
`, /*line write.go:29*/ file /*line write.go:32*/, pkg /*line write.go:36*/, v_qd, typ /*line write.go:37*/, v_qd)
//line write.go:38
	for _, name := range names {
//line write.go:39
		fmt.Printf(`	case %v:
		return "%v"
`, /*line write.go:39*/ name /*line write.go:40*/, name)
//line write.go:41
	}
//line write.go:42
	fmt.Printf(`	}
	return fmt.Sprintf("%v(%%d)", %v)
}
`, /*line write.go:43*/ typ, v_qd)
//line write.go:45
}
