// Code generated by qudy from write.go. DO NOT EDIT.

//go:build !qudy

package main

import "fmt"

// writeParse writes the file with the function that parses an enum's constant names.
func writeParse(file, pkg, typ string, names []string) {
	qudyGensym := func() func(string) string {
		counts := map[string]int{}
		return func(want string) string {
			counts[want]++
			digits := ""
			for n := counts[want]; n > 0; n /= 10 {
				digits = string(rune('0'+n%10)) + digits
			}
			return want + "_qd" + digits
		}
	}()
	s_qd := qudyGensym("s")
	fmt.Printf(`-- %v_parse.go --
// Code generated by the qudy enums example. DO NOT EDIT.

package %v

import "fmt"

// Parse%v returns the %v with the given name.
func Parse%v(%v string) (%v, error) {
	switch %v {
`, file, pkg, typ, typ, typ, s_qd, typ, s_qd)
	for _, name := range names {
		fmt.Printf(`	case "%v":
		return %v, nil
`, name, name)
	}
	zero_qd := qudyGensym("zero")
	fmt.Printf(`	}
	var %v %v
	return %v, fmt.Errorf("%v has no constant named %%q", %v)
}
`, zero_qd, typ, zero_qd, typ, s_qd)
}

// writeString writes the file with an enum's String method.
func writeString(file, pkg, typ string, names []string) {
	qudyGensym := func() func(string) string {
		counts := map[string]int{}
		return func(want string) string {
			counts[want]++
			digits := ""
			for n := counts[want]; n > 0; n /= 10 {
				digits = string(rune('0'+n%10)) + digits
			}
			return want + "_qd" + digits
		}
	}()
	v_qd := qudyGensym("v")
	fmt.Printf(`-- %v_string.go --
// Code generated by the qudy enums example. DO NOT EDIT.

package %v

import "fmt"

func (%v %v) String() string {
	switch %v {
`, file, pkg, v_qd, typ, v_qd)
	for _, name := range names {
		fmt.Printf(`	case %v:
		return "%v"
`, name, name)
	}
	fmt.Printf(`	}
	return fmt.Sprintf("%v(%%d)", %v)
}
`, typ, v_qd)
}
