// Code generated by qudy from write.go. DO NOT EDIT.

//go:build !qudy

package main

import "fmt"

// writeParse writes the file with the function that parses an enum's constant names.
func writeParse(file, pkg, typ string, names []string) {
	qudyGensym := func() func(string) string {
		counts := map[string]int{}
		return func(want string) string {
			counts[want]++
			digits := ""
			for n := counts[want]; n > 0; n /= 10 {
				digits = string(rune('0'+n%10)) + digits
			}
			return want + "_qd" + digits
		}
	}()
	s := qudyGensym("s")
	fmt.Printf(`-- %s_parse.go --
// Code generated by the qudy enums example. DO NOT EDIT.

package %s

import "fmt"

// Parse%s returns the %s with the given name.
func Parse%s(%s string) (%s, error) {
	switch %s {
`, file, pkg, typ, typ, typ, s, typ, s)
	for _, name := range names {
		fmt.Printf(`	case "%s":
		return %s, nil
`, name, name)
	}
	zero := qudyGensym("zero")
	fmt.Printf(`	}
	var %s %s
	return %s, fmt.Errorf("%s has no constant named %%q", %s)
}
`, zero, typ, zero, typ, s)
}

// writeString writes the file with an enum's String method.
func writeString(file, pkg, typ string, names []string) {
	qudyGensym := func() func(string) string {
		counts := map[string]int{}
		return func(want string) string {
			counts[want]++
			digits := ""
			for n := counts[want]; n > 0; n /= 10 {
				digits = string(rune('0'+n%10)) + digits
			}
			return want + "_qd" + digits
		}
	}()
	v := qudyGensym("v")
	fmt.Printf(`-- %s_string.go --
// Code generated by the qudy enums example. DO NOT EDIT.

package %s

import "fmt"

func (%s %s) String() string {
	switch %s {
`, file, pkg, v, typ, v)
	for _, name := range names {
		fmt.Printf(`	case %s:
		return "%s"
`, name, name)
	}
	fmt.Printf(`	}
	return fmt.Sprintf("%s(%%d)", %s)
}
`, typ, v)
}
