//go:build qudy

package main

import "fmt"

// writeParse writes the file with the function that parses an enum's constant names.
func writeParse(file, pkg, typ string, names []string) {
	//`-- ~{file}_parse.go --
	//`// Code generated by the qudy enums example. DO NOT EDIT.
	//`
	//`package ~pkg
	//`
	//`import "fmt"
	//`
	//`// Parse~typ returns the ~typ with the given name.
	//`func Parse~typ(s# string) (~typ, error) {
	//`	switch s# {
	for _, name := range names {
		//`	case "~name":
		//`		return ~name, nil
	}
	//`	}
	//`	var zero# ~typ
	//`	return zero#, fmt.Errorf("~typ has no constant named %q", s#)
	//`}
}

// writeString writes the file with an enum's String method.
func writeString(file, pkg, typ string, names []string) {
	//`-- ~{file}_string.go --
	//`// Code generated by the qudy enums example. DO NOT EDIT.
	//`
	//`package ~pkg
	//`
	//`import "fmt"
	//`
	//`func (v# ~typ) String() string {
	//`	switch v# {
	for _, name := range names {
		//`	case ~name:
		//`		return "~name"
	}
	//`	}
	//`	return fmt.Sprintf("~typ(%d)", v#)
	//`}
}
