// Command qudy compiles a template into the Go source of its generator.
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/bilus/qudy"
)

func main() {
	emit := flag.String("emit", "fmt.Printf", "the emit function: the function of the generator that writes a run of output lines")
	out := flag.String("o", "", "the file for the generator, or with -txtar the directory for the files")
	runtime := flag.Bool("runtime", false, "also write qudy_runtime.go, with qudyCapture, qudyPush and one symbol generator for the package")
	extract := flag.Bool("txtar", false, "read a txtar archive from standard input and write its files, gofmt-formatted")
	flag.Parse()
	var err error
	switch {
	case *extract && flag.NArg() == 0:
		err = extractArchive(*out)
	case !*extract && flag.NArg() == 1 && *out != "":
		err = compileFile(flag.Arg(0), *out, *emit, *runtime)
	default:
		fmt.Fprintln(os.Stderr, "usage: qudy [-emit func] [-runtime] -o out.go template.go")
		fmt.Fprintln(os.Stderr, "       qudy -txtar [-o dir] < archive")
		os.Exit(2)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "qudy:", err)
		os.Exit(1)
	}
}

// runtimeName is the name of the runtime file, beside the generator.
const runtimeName = "qudy_runtime.go"

// compileFile compiles one template and writes the generator, and the runtime file on request.
func compileFile(template, out, emit string, runtime bool) error {
	src, err := os.ReadFile(template)
	if err != nil {
		return err
	}
	var gen, support []byte
	if runtime {
		gen, support, err = qudy.CompileWithRuntime(template, src, emit)
	} else {
		gen, err = qudy.Compile(template, src, emit)
	}
	if err != nil {
		return err
	}
	header := fmt.Sprintf("// Code generated by qudy from %s. DO NOT EDIT.\n\n", template)
	if err := os.WriteFile(out, append([]byte(header), gen...), 0o644); err != nil {
		return err
	}
	if support == nil {
		return nil
	}
	return os.WriteFile(filepath.Join(filepath.Dir(out), runtimeName), support, 0o644)
}

// extractArchive writes the files of the archive on standard input under dir.
func extractArchive(dir string) error {
	archive, err := io.ReadAll(os.Stdin)
	if err != nil {
		return err
	}
	comment, err := qudy.Extract(archive, dir)
	if err != nil {
		return err
	}
	_, err = os.Stdout.Write(comment)
	return err
}
