// Command qudy compiles a template into the Go source of its generator.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/bilus/qudy"
)

func main() {
	emit := flag.String("emit", "g.generate", "the emit function: the function of the generator that writes a run of output lines")
	symbols := flag.String("symbols", "", "the symbol generator, as variable,create,method; create is empty when the template declares the variable")
	out := flag.String("o", "", "the file for the generator")
	flag.Parse()
	if flag.NArg() != 1 || *out == "" {
		fmt.Fprintln(os.Stderr, "usage: qudy [-emit func] [-symbols variable,create,method] -o out.go template.go")
		os.Exit(2)
	}
	if err := compileFile(flag.Arg(0), *out, *emit, *symbols); err != nil {
		fmt.Fprintln(os.Stderr, "qudy:", err)
		os.Exit(1)
	}
}

// compileFile compiles one template and writes the generator after a Code generated comment.
func compileFile(template, out, emit, symbolsFlag string) error {
	symbols, err := parseSymbolGenerator(symbolsFlag)
	if err != nil {
		return err
	}
	src, err := os.ReadFile(template)
	if err != nil {
		return err
	}
	gen, err := qudy.Compile(template, src, emit, symbols)
	if err != nil {
		return err
	}
	header := fmt.Sprintf("// Code generated by qudy from %s. DO NOT EDIT.\n\n", template)
	return os.WriteFile(out, append([]byte(header), gen...), 0o644)
}

// parseSymbolGenerator parses the -symbols flag, empty for a template without gensyms.
func parseSymbolGenerator(flag string) (qudy.SymbolGenerator, error) {
	if flag == "" {
		return qudy.SymbolGenerator{}, nil
	}
	parts := strings.Split(flag, ",")
	if len(parts) != 3 {
		return qudy.SymbolGenerator{}, fmt.Errorf("-symbols takes variable,create,method, got %q", flag)
	}
	return qudy.NewSymbolGenerator(parts[0], parts[1], parts[2]), nil
}
