// Command qudy compiles a template into the Go source of its generator.
package main

import (
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/bilus/qudy"
)

func main() {
	emit := flag.String("emit", "g.generate", "the emit function: the function of the generator that writes a run of output lines")
	out := flag.String("o", "", "the file for the generator, or with -txtar the directory for the files")
	extract := flag.Bool("txtar", false, "read a txtar archive from standard input and write its files, gofmt-formatted")
	flag.Parse()
	var err error
	switch {
	case *extract && flag.NArg() == 0:
		err = extractArchive(*out)
	case !*extract && flag.NArg() == 1 && *out != "":
		err = compileFile(flag.Arg(0), *out, *emit)
	default:
		fmt.Fprintln(os.Stderr, "usage: qudy [-emit func] -o out.go template.go")
		fmt.Fprintln(os.Stderr, "       qudy -txtar [-o dir] < archive")
		os.Exit(2)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "qudy:", err)
		os.Exit(1)
	}
}

// compileFile compiles one template and writes the generator after a Code generated comment.
func compileFile(template, out, emit string) error {
	src, err := os.ReadFile(template)
	if err != nil {
		return err
	}
	gen, err := qudy.Compile(template, src, emit)
	if err != nil {
		return err
	}
	header := fmt.Sprintf("// Code generated by qudy from %s. DO NOT EDIT.\n\n", template)
	return os.WriteFile(out, append([]byte(header), gen...), 0o644)
}

// extractArchive writes the files of the archive on standard input under dir.
func extractArchive(dir string) error {
	archive, err := io.ReadAll(os.Stdin)
	if err != nil {
		return err
	}
	comment, err := qudy.Extract(archive, dir)
	if err != nil {
		return err
	}
	_, err = os.Stdout.Write(comment)
	return err
}
