//go:build qudy || generate

// Command stringer writes the String method of an enum, as an example of qudy.
package main

//go:generate go run ../../cmd/qudy -emit fmt.Printf -o stringer_gen.go stringer.go

import (
	"flag"
	"fmt"
	"os"
)

func main() {
	pkg := flag.String("package", "main", "the package of the generated file")
	typ := flag.String("type", "", "the enum type")
	flag.Parse()
	if *typ == "" || flag.NArg() == 0 {
		fmt.Fprintln(os.Stderr, "usage: stringer [-package name] -type T constant...")
		os.Exit(2)
	}
	writeStringer(*pkg, *typ, flag.Args())
}

// writeStringer writes an enum's String method and its guard against changed constants.
func writeStringer(pkg, typ string, names []string) {
	//`// Code generated by the qudy stringer example. DO NOT EDIT.
	//`
	//`package ~pkg
	//`
	//`import "fmt"
	//`
	//`func (v# ~typ) String() string {
	//`	switch v# {
	for _, name := range names {
		//`	case ~name:
		//`		return "~name"
	}
	//`	}
	//`	return fmt.Sprintf("~typ(%d)", v#)
	//`}
	//`
	//`func _() {
	//`	// An "invalid array index" error means that a constant's value changed.
	//`	var x# [1]struct{}
	for i, name := range names {
		//`	_ = x#[~name-~i]
	}
	//`}
}
