// Code generated by qudy from stringer.go. DO NOT EDIT.

//go:build !qudy || generate

// Command stringer writes the String method of an enum, as an example of qudy.
//
//line stringer.go:4
package main

//line stringer.go:8
import (
	"flag"
	"fmt"
	"os"
)

func main() {
	pkg := flag.String("package", "main", "the package of the generated file")
	typ := flag.String("type", "", "the enum type")
	flag.Parse()
	if *typ == "" || flag.NArg() == 0 {
		fmt.Fprintln(os.Stderr, "usage: stringer [-package name] -type T constant...")
		os.Exit(2)
	}
	writeStringer(*pkg, *typ, flag.Args())
}

// writeStringer writes an enum's String method and its guard against changed constants.
func writeStringer(pkg, typ string, names []string) {
	qudyGensym := func() func(string) string {
		count := 0
		gensym := func(want string) string {
			count++
			digits := ""
			for n := count; n > 0; n /= 10 {
				digits = string(rune('0'+n%10)) + digits
			}
			return want + "_qd" + digits
		}
		return gensym
	}()
	v_qd := qudyGensym("v")
//line stringer.go:27
	fmt.Printf(`// Code generated by the qudy stringer example. DO NOT EDIT.

package %v

import "fmt"

func (%v %v) String() string {
	switch %v {
`, /*line stringer.go:29*/ pkg /*line stringer.go:33*/, v_qd, typ /*line stringer.go:34*/, v_qd)
//line stringer.go:35
	for _, name := range names {
//line stringer.go:36
		fmt.Printf(`	case %v:
		return "%v"
`, /*line stringer.go:36*/ name /*line stringer.go:37*/, name)
//line stringer.go:38
	}
	x_qd := qudyGensym("x")
//line stringer.go:39
	fmt.Printf(`	}
	return fmt.Sprintf("%v(%%d)", %v)
}

func _() {
	// An "invalid array index" error means that a constant's value changed.
	var %v [1]struct{}
`, /*line stringer.go:40*/ typ, v_qd /*line stringer.go:45*/, x_qd)
//line stringer.go:46
	for i, name := range names {
//line stringer.go:46
		fmt.Printf(`	_ = %v[%v-%v]
`, x_qd, name, i)
//line stringer.go:48
	}
//line stringer.go:48
	fmt.Printf(`}
`)
//line stringer.go:50
}
