// Code generated by qudy from stringer.go. DO NOT EDIT.

//go:build !qudy || generate

// Command stringer writes the String method of an enum, as an example of qudy.
package main

import (
	"flag"
	"fmt"
	"os"
)

func main() {
	pkg := flag.String("package", "main", "the package of the generated file")
	typ := flag.String("type", "", "the enum type")
	flag.Parse()
	if *typ == "" || flag.NArg() == 0 {
		fmt.Fprintln(os.Stderr, "usage: stringer [-package name] -type T constant...")
		os.Exit(2)
	}
	writeStringer(*pkg, *typ, flag.Args())
}

// writeStringer writes an enum's String method and its guard against changed constants.
func writeStringer(pkg, typ string, names []string) {
	qudyGensym := func() func(string) string {
		counts := map[string]int{}
		return func(want string) string {
			counts[want]++
			digits := ""
			for n := counts[want]; n > 0; n /= 10 {
				digits = string(rune('0'+n%10)) + digits
			}
			return want + "_qd" + digits
		}
	}()
	v_qd := qudyGensym("v")
	fmt.Printf(`// Code generated by the qudy stringer example. DO NOT EDIT.

package %v

import "fmt"

func (%v %v) String() string {
	switch %v {
`, pkg, v_qd, typ, v_qd)
	for _, name := range names {
		fmt.Printf(`	case %v:
		return "%v"
`, name, name)
	}
	x_qd := qudyGensym("x")
	fmt.Printf(`	}
	return fmt.Sprintf("%v(%%d)", %v)
}

func _() {
	// An "invalid array index" error means that a constant's value changed.
	var %v [1]struct{}
`, typ, v_qd, x_qd)
	for i, name := range names {
		fmt.Printf(`	_ = %v[%v-%v]
`, x_qd, name, i)
	}
	fmt.Printf(`}
`)
}
