//go:build qudy && go1.27

package sumtype

// writeHeader writes the generated file's header and package clause.
func (g *writer) writeHeader(source, pkg string) {
	//`// Code generated by sumtype from ~source. DO NOT EDIT.
	//`
	//`package ~pkg
}

// writeSum writes the declarations of one sum type.
func (g *writer) writeSum(sum sumType) {
	qudyGensym := newSymbolGenerator(sum.variants).gensym
	iface, marker := sum.variantInterface(), sum.markerMethod()
	//`
	//`// ~iface is the closed set of ~sum.name's variants.
	//`type ~iface interface{ ~marker() }
	//`
	for _, v := range sum.variants {
		//`func (~v) ~marker() {}
	}
	//`
	//`// ~sum.name is one of its variants, and ~sum.defaultVariant when it is the zero value.
	//`type ~sum.name struct{ v ~iface }
	//`
	//`// ~{sum.constraint()} constrains a type to ~sum.name's variants.
	//`type ~{sum.constraint()} interface {
	//`	~{sum.union()}
	//`	~iface
	//`}
	//`
	//`// ~{sum.constructor()} wraps a variant in a ~sum.name.
	//`func ~{sum.constructor()}[V ~{sum.constraint()}](v V) ~sum.name { return ~sum.name{v: v} }
	//`
	//`// Match calls the function for the ~sum.name's variant.
	//`func (s# ~sum.name) Match[R# any](
	for _, v := range sum.variants {
		//`	~{branch(v)} func(~v) R#,
	}
	//`) R# {
	//`	switch v := s#.v.(type) {
	for _, v := range sum.variants {
		//`	case ~v:
		//`		return ~{branch(v)}(v)
	}
	//`	}
	//`	var zero ~sum.defaultVariant
	//`	return ~{branch(sum.defaultVariant)}(zero)
	//`}
}
