// Code generated by qudy from write.go. DO NOT EDIT.

//go:build !qudy && go1.27

package sumtype

// writeHeader writes the generated file's header and package clause.
func (g *writer) writeHeader(source, pkg string) {
	g.generate(`// Code generated by sumtype from %v. DO NOT EDIT.

package %v
`, source, pkg)
}

// writeSum writes the declarations of one sum type.
func (g *writer) writeSum(sum sumType) {
	qudyGensym := newSymbolGenerator(sum.variants).gensym
	iface, marker := sum.variantInterface(), sum.markerMethod()
	g.generate(`
// %v is the closed set of %v's variants.
type %v interface{ %v() }

`, iface, sum.name, iface, marker)
	for _, v := range sum.variants {
		g.generate(`func (%v) %v() {}
`, v, marker)
	}
	s := qudyGensym("s")
	R := qudyGensym("R")
	g.generate(`
// %v is one of its variants, and %v when it is the zero value.
type %v struct{ v %v }

// %v constrains a type to %v's variants.
type %v interface {
	%v
	%v
}

// %v wraps a variant in a %v.
func %v[V %v](v V) %v { return %v{v: v} }

// Match calls the function for the %v's variant.
func (%v %v) Match[%v any](
`, sum.name, sum.defaultVariant, sum.name, iface, sum.constraint(), sum.name, sum.constraint(), sum.union(), iface, sum.constructor(), sum.name, sum.constructor(), sum.constraint(), sum.name, sum.name, sum.name, s, sum.name, R)
	for _, v := range sum.variants {
		g.generate(`	%v func(%v) %v,
`, branch(v), v, R)
	}
	g.generate(`) %v {
	switch v := %v.v.(type) {
`, R, s)
	for _, v := range sum.variants {
		g.generate(`	case %v:
		return %v(v)
`, v, branch(v))
	}
	g.generate(`	}
	var zero %v
	return %v(zero)
}
`, sum.defaultVariant, branch(sum.defaultVariant))
}
