// Code generated by qudy from write.go. DO NOT EDIT.

//go:build !qudy && go1.27

//line write.go:3
package sumtype

// writeHeader writes the generated file's header and package clause.
func (g *writer) writeHeader(source, pkg string) {
//line write.go:7
	g.generate(`// Code generated by sumtype from %v. DO NOT EDIT.

package %v
`, /*line write.go:7*/ source /*line write.go:9*/, pkg)
//line write.go:10
}

// writeSum writes the declarations of one sum type.
func (g *writer) writeSum(sum sumType) {
	qudyGensym := newSymbolGenerator(sum.variants).gensym
	iface, marker := sum.variantInterface(), sum.markerMethod()
//line write.go:16
	g.generate(`
// %v is the closed set of %v's variants.
type %v interface{ %v() }

`, /*line write.go:17*/ iface, sum.name /*line write.go:18*/, iface, marker)
//line write.go:20
	for _, v := range sum.variants {
//line write.go:20
		g.generate(`func (%v) %v() {}
`, v, marker)
//line write.go:22
	}
	s_qd := qudyGensym("s")
	R_qd := qudyGensym("R")
//line write.go:23
	g.generate(`
// %v is one of its variants, and %v when it is the zero value.
type %v struct{ v %v }

// %v constrains a type to %v's variants.
type %v interface {
	%v
	%v
}

// %v wraps a variant in a %v.
func %v[V %v](v V) %v { return %v{v: v} }

// Match calls the function for the %v's variant.
func (%v %v) Match[%v any](
`, /*line write.go:24*/ sum.name, sum.defaultVariant /*line write.go:25*/, sum.name, iface /*line write.go:27*/, sum.constraint(), sum.name /*line write.go:28*/, sum.constraint() /*line write.go:29*/, sum.union() /*line write.go:30*/, iface /*line write.go:33*/, sum.constructor(), sum.name /*line write.go:34*/, sum.constructor(), sum.constraint(), sum.name, sum.name /*line write.go:36*/, sum.name /*line write.go:37*/, s_qd, sum.name, R_qd)
//line write.go:38
	for _, v := range sum.variants {
//line write.go:38
		g.generate(`	%v func(%v) %v,
`, branch(v), v, R_qd)
//line write.go:40
	}
//line write.go:41
	g.generate(`) %v {
	switch v := %v.v.(type) {
`, /*line write.go:41*/ R_qd /*line write.go:42*/, s_qd)
//line write.go:43
	for _, v := range sum.variants {
//line write.go:44
		g.generate(`	case %v:
		return %v(v)
`, /*line write.go:44*/ v /*line write.go:45*/, branch(v))
//line write.go:46
	}
//line write.go:47
	g.generate(`	}
	var zero %v
	return %v(zero)
}
`, /*line write.go:48*/ sum.defaultVariant /*line write.go:49*/, branch(sum.defaultVariant))
//line write.go:51
}
